name: Daily Inspiration Email

on:
  schedule:
    - cron: '23 23 * * *'  # GitHub Actions uses UTC; 23:23 UTC = 1:23 AM GMT+2
  workflow_dispatch:      # Allows manual run from Actions tab

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -o daily-email main.go

      - name: Run the app
        env:
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
        run: ./daily-email
