name: Daily Inspiration Email

on:
  schedule:
    - cron: '0 6 * * *' 
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'
      
      - name: Clear Go build cache
        run: go clean -modcache

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -o daily-email main.go

      - name: Run the app
        env:
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          FROM_EMAIL_PASSWORD: ${{ secrets.FROM_EMAIL_PASSWORD }}
          UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
        run: ./daily-email
